### ISSUE TITLE
RMC setup output file location seems not working properly

### ISSUE THREAD

**Issue by Kvieta1990** [AdvancedPhotonSource/GSASII-copy#4]
When creating RMC setup files within the GSAS-II interface for a selected phase, it seems that the location of the generated output file is not self-consistent -- sometimes those files appear under home directory, and sometimes they appear in the location where GSAS-II is launched.

**Comment by briantoby** [comment]
This was addressed by Bob in https://subversion.xray.aps.anl.gov/trac/pyGSAS/changeset/5523 and https://subversion.xray.aps.anl.gov/trac/pyGSAS/changeset/5527
